module.exports = [
    {
        city: "Delhi",
        latitude: "28.6600",
        longitude: "77.2300",
        country: "India",
        state: "Delhi",
    },
    {
        city: "Mumbai",
        latitude: "18.9667",
        longitude: "72.8333",
        country: "India",
        state: "Maharashtra",
    },
    {
        city: "Kolkata",
        latitude: "22.5411",
        longitude: "88.3378",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Bangalore",
        latitude: "12.9699",
        longitude: "77.5980",
        country: "India",
        state: "Karnataka",
    },
    {
        city: "Chennai",
        latitude: "13.0825",
        longitude: "80.2750",
        country: "India",
        state: "Tamil Nadu",

    },
    {
        city: "Hyderabad",
        latitude: "17.3667",
        longitude: "78.4667",
        country: "India",
        state: "Telangana",
    },
    {
        city: "Pune",
        latitude: "18.5196",
        longitude: "73.8553",
        country: "India",
        state: "Maharashtra",
    },
    {
        city: "Ahmedabad",
        latitude: "23.0300",
        longitude: "72.5800",
        country: "India",
        state: "Gujarat",
    },
    {
        city: "Sūrat",
        latitude: "21.1700",
        longitude: "72.8300",
        country: "India",
        state: "Gujarat",
    },
    {
        city: "Lucknow",
        latitude: "26.8470",
        longitude: "80.9470",
        country: "India",
        state: "Uttar Pradesh",
    },
    {
        city: "Jaipur",
        latitude: "26.9167",
        longitude: "75.8667",
        country: "India",
        state: "Rajasthan",
    },
    {
        city: "Cawnpore",
        latitude: "26.4725",
        longitude: "80.3311",
        country: "India",
        state: "Uttar Pradesh",
    },
    {
        city: "Mirzapur",
        latitude: "25.1500",
        longitude: "82.5800",
        country: "India",
        state: "Uttar Pradesh",
    },
    {
        city: "Nagpur",
        latitude: "21.1539",
        longitude: "79.0831",
        country: "India",
        state: "Maharashtra",
    },
    {
        city: "Ghaziabad",
        latitude: "28.6667",
        longitude: "77.4167",
        country: "India",
        state: "Uttar Pradesh",
    },
    {
        city: "Indore",
        latitude: "22.7206",
        longitude: "75.8472",
        country: "India",
        state: "Madhya Pradesh",
    },
    {
        city: "Vadodara",
        latitude: "22.3000",
        longitude: "73.2000",
        country: "India",
        state: "Gujarat",
    },
    {
        city: "Vishakhapatnam",
        latitude: "17.7333",
        longitude: "83.3167",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Bhopal",
        latitude: "23.2500",
        longitude: "77.4167",
        country: "India",
        state: "Madhya Pradesh",
    },
    {
        city: "Chinchvad",
        latitude: "18.6278",
        longitude: "73.8131",
        country: "India",
        state: "Maharashtra",
    },
    {
        city: "Patna",
        latitude: "25.6100",
        longitude: "85.1414",
        country: "India",
        state: "Bihar",
    },
    {
        city: "Ludhiana",
        latitude: "30.9083",
        longitude: "75.8486",
        country: "India",
        state: "Punjab",
    },
    {
        city: "agra",
        latitude: "27.1800",
        longitude: "78.0200",
        country: "India",
        state: "Uttar Pradesh",
    },
    {
        city: "Kalyan",
        latitude: "19.2502",
        longitude: "73.1602",
        country: "India",
        state: "Maharashtra",
    },
    {
        city: "Madurai",
        latitude: "9.9197",
        longitude: "78.1194",
        country: "India",
        state: "Tamil Nadu",
    },
    {
        city: "Jamshedpur",
        latitude: "22.8000",
        longitude: "86.1833",
        country: "India",
        state: "Jharkhand",
    },
    {
        city: "Nasik",
        latitude: "20.0000",
        longitude: "73.7833",
        country: "India",
        state: "Maharashtra",
    },
    {
        city: "Faridabad",
        latitude: "28.4333",
        longitude: "77.3167",
        country: "India",
        state: "Haryana",
    },
    {
        city: "Aurangabad",
        latitude: "19.8800",
        longitude: "75.3200",
        country: "India",
        state: "Maharashtra",
    },
    {
        city: "Rajkot",
        latitude: "22.2969",
        longitude: "70.7984",
        country: "India",
        state: "Gujarat",
    },
    {
        city: "Meerut",
        latitude: "28.9900",
        longitude: "77.7000",
        country: "India",
        state: "Uttar Pradesh",
    },
    {
        city: "Jabalpur",
        latitude: "23.1667",
        longitude: "79.9333",
        country: "India",
        state: "Madhya Pradesh",
    },
    {
        city: "Thane",
        latitude: "19.1800",
        longitude: "72.9633",
        country: "India",
        state: "Maharashtra",
    },
    {
        city: "Dhanbad",
        latitude: "23.7928",
        longitude: "86.4350",
        country: "India",
        state: "Jharkhand",
    },
    {
        city: "Allahabad",
        latitude: "25.4550",
        longitude: "81.8400",
        country: "India",
        state: "Uttar Pradesh",
    },
    {
        city: "Varanasi",
        latitude: "25.3189",
        longitude: "83.0128",
        country: "India",
        state: "Uttar Pradesh",
    },
    {
        city: "Srinagar",
        latitude: "34.0911",
        longitude: "74.8061",
        country: "India",
        state: "Jammu and Kashmir",
    },
    {
        city: "Amritsar",
        latitude: "31.6167",
        longitude: "74.8500",
        country: "India",
        state: "Punjab",
    },
    {
        city: "Aligarh",
        latitude: "27.8800",
        longitude: "78.0800",
        country: "India",
        state: "Uttar Pradesh",
    },
    {
        city: "Bhiwandi",
        latitude: "19.3000",
        longitude: "73.0667",
        country: "India",
        state: "Maharashtra",
    },
    {
        city: "Gwalior",
        latitude: "26.2150",
        longitude: "78.1931",
        country: "India",
        state: "Madhya Pradesh",
    },
    {
        city: "Bhilai",
        latitude: "21.2167",
        longitude: "81.4333",
        country: "India",
        state: "Chhattisgarh",
    },
    {
        city: "Haora",
        latitude: "22.5900",
        longitude: "88.3100",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Ranchi",
        latitude: "23.3556",
        longitude: "85.3347",
        country: "India",
        state: "Jharkhand",
    },
    {
        city: "Bezwada",
        latitude: "16.5167",
        longitude: "80.6167",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Chandigarh",
        latitude: "30.7353",
        longitude: "76.7911",
        country: "India",
        state: "Chandigarh",
    },
    {
        city: "Mysore",
        latitude: "12.3086",
        longitude: "76.6531",
        country: "India",
        state: "Karnataka",
    },
    {
        city: "Raipur",
        latitude: "21.2379",
        longitude: "81.6337",
        country: "India",
        state: "Chhattisgarh",
    },
    {
        city: "Kota",
        latitude: "25.1800",
        longitude: "75.8300",
        country: "India",
        state: "Rajasthan",
    },
    {
        city: "Bareilly",
        latitude: "28.3640",
        longitude: "79.4150",
        country: "India",
        state: "Uttar Pradesh",
    },
    {
        city: "Jodhpur",
        latitude: "26.2918",
        longitude: "73.0168",
        country: "India",
        state: "Rajasthan",
    },
    {
        city: "Coimbatore",
        latitude: "11.0000",
        longitude: "76.9667",
        country: "India",
        state: "Tamil Nadu",
    },
    {
        city: "Dispur",
        latitude: "26.1500",
        longitude: "91.7700",
        country: "India",
        state: "Assam",
    },
    {
        city: "Guwahati",
        latitude: "26.1667",
        longitude: "91.7667",
        country: "India",
        state: "Assam",
    },
    {
        city: "Solapur",
        latitude: "17.6833",
        longitude: "75.9167",
        country: "India",
        state: "Maharashtra",
    },
    {
        city: "Trichinopoly",
        latitude: "10.8269",
        longitude: "78.6928",
        country: "India",
        state: "Tamil Nadu",
    },
    {
        city: "Hubli",
        latitude: "15.3600",
        longitude: "75.1250",
        country: "India",
        state: "Karnataka",
    },
    {
        city: "Jalandhar",
        latitude: "31.3256",
        longitude: "75.5792",
        country: "India",
        state: "Punjab",
    },
    {
        city: "Bhubaneshwar",
        latitude: "20.2644",
        longitude: "85.8281",
        country: "India",
        state: "Odisha",
    },
    {
        city: "Bhayandar",
        latitude: "19.3000",
        longitude: "72.8500",
        country: "India",
        state: "Maharashtra",
    },
    {
        city: "Moradabad",
        latitude: "28.8418",
        longitude: "78.7568",
        country: "India",
        state: "Uttar Pradesh",
    },
    {
        city: "Kolhapur",
        latitude: "16.7000",
        longitude: "74.2333",
        country: "India",
        state: "Maharashtra",
    },
    {
        city: "Thiruvananthapuram",
        latitude: "8.5000",
        longitude: "76.8997",
        country: "India",
        state: "Kerala",
    },
    {
        city: "Saharanpur",
        latitude: "29.9640",
        longitude: "77.5460",
        country: "India",
        state: "Uttar Pradesh",
    },
    {
        city: "Warangal",
        latitude: "17.9756",
        longitude: "79.6011",
        country: "India",
        state: "Telangana",
    },
    {
        city: "Salem",
        latitude: "11.6500",
        longitude: "78.1667",
        country: "India",
        state: "Tamil Nadu",
    },
    {
        city: "Malegaon",
        latitude: "20.5500",
        longitude: "74.5500",
        country: "India",
        state: "Maharashtra",
    },
    {
        city: "Kochi",
        latitude: "9.9667",
        longitude: "76.2833",
        country: "India",
        state: "Kerala",
    },
    {
        city: "Gorakhpur",
        latitude: "26.7611",
        longitude: "83.3667",
        country: "India",
        state: "Uttar Pradesh",
    },
    {
        city: "Shimoga",
        latitude: "13.9304",
        longitude: "75.5600",
        country: "India",
        state: "Karnataka",
    },
    {
        city: "Tiruppūr",
        latitude: "11.1075",
        longitude: "77.3398",
        country: "India",
        state: "Tamil Nadu",
    },
    {
        city: "Guntūr",
        latitude: "16.3000",
        longitude: "80.4500",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Raurkela",
        latitude: "22.2492",
        longitude: "84.8828",
        country: "India",
        state: "Odisha",
    },
    {
        city: "Mangalore",
        latitude: "12.8703",
        longitude: "74.8806",
        country: "India",
        state: "Karnataka",
    },
    {
        city: "Nanded",
        latitude: "19.1500",
        longitude: "77.3333",
        country: "India",
        state: "Maharashtra",
    },
    {
        city: "Cuttack",
        latitude: "20.4500",
        longitude: "85.8667",
        country: "India",
        state: "Odisha",
    },
    {
        city: "Chanda",
        latitude: "19.9500",
        longitude: "79.3000",
        country: "India",
        state: "Maharashtra",
    },
    {
        city: "Dehra Dūn",
        latitude: "30.3180",
        longitude: "78.0290",
        country: "India",
        state: "Uttarakhand",
    },
    {
        city: "Durgapur",
        latitude: "23.5500",
        longitude: "87.3200",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "asansol",
        latitude: "23.6833",
        longitude: "86.9667",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Bhavnagar",
        latitude: "21.7650",
        longitude: "72.1369",
        country: "India",
        state: "Gujarat",
    },
    {
        city: "Amravati",
        latitude: "20.9333",
        longitude: "77.7500",
        country: "India",
        state: "Maharashtra",
    },
    {
        city: "Nellore",
        latitude: "14.4333",
        longitude: "79.9667",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Ajmer",
        latitude: "26.4680",
        longitude: "74.6390",
        country: "India",
        state: "Rajasthan",
    },
    {
        city: "Tinnevelly",
        latitude: "8.7289",
        longitude: "77.7081",
        country: "India",
        state: "Tamil Nadu",
    },
    {
        city: "Bikaner",
        latitude: "28.0181",
        longitude: "73.3169",
        country: "India",
        state: "Rajasthan",
    },
    {
        city: "Agartala",
        latitude: "23.8333",
        longitude: "91.2667",
        country: "India",
        state: "Tripura",
    },
    {
        city: "Ujjain",
        latitude: "23.1828",
        longitude: "75.7772",
        country: "India",
        state: "Madhya Pradesh",
    },
    {
        city: "Jhansi",
        latitude: "25.4486",
        longitude: "78.5696",
        country: "India",
        state: "Uttar Pradesh",
    },
    {
        city: "Ulhasnagar",
        latitude: "19.2167",
        longitude: "73.1500",
        country: "India",
        state: "Maharashtra",
    },
    {
        city: "Davangere",
        latitude: "14.4667",
        longitude: "75.9167",
        country: "India",
        state: "Karnataka",
    },
    {
        city: "Jammu",
        latitude: "32.7333",
        longitude: "74.8500",
        country: "India",
        state: "Jammu and Kashmir",
    },
    {
        city: "Belgaum",
        latitude: "15.8667",
        longitude: "74.5000",
        country: "India",
        state: "Karnataka",
    },
    {
        city: "Gulbarga",
        latitude: "17.3333",
        longitude: "76.8333",
        country: "India",
        state: "Karnataka",
    },
    {
        city: "Jamnagar",
        latitude: "22.4700",
        longitude: "70.0700",
        country: "India",
        state: "Gujarat",
    },
    {
        city: "Dhūlia",
        latitude: "20.9000",
        longitude: "74.7833",
        country: "India",
        state: "Maharashtra",
    },
    {
        city: "Gaya",
        latitude: "24.7500",
        longitude: "85.0167",
        country: "India",
        state: "Bihar",
    },
    {
        city: "Jalgaon",
        latitude: "21.0167",
        longitude: "75.5667",
        country: "India",
        state: "Maharashtra",
    },
    {
        city: "Kurnool",
        latitude: "15.8222",
        longitude: "78.0350",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Udaipur",
        latitude: "24.5833",
        longitude: "73.6833",
        country: "India",
        state: "Rajasthan",
    },
    {
        city: "Bellary",
        latitude: "15.1500",
        longitude: "76.9150",
        country: "India",
        state: "Karnataka",
    },
    {
        city: "Sangli",
        latitude: "16.8667",
        longitude: "74.5667",
        country: "India",
        state: "Maharashtra",
    },
    {
        city: "Tuticorin",
        latitude: "8.7833",
        longitude: "78.1333",
        country: "India",
        state: "Tamil Nadu",
    },
    {
        city: "Calicut",
        latitude: "11.2500",
        longitude: "75.7667",
        country: "India",
        state: "Kerala",
    },
    {
        city: "Akola",
        latitude: "20.7333",
        longitude: "77.0000",
        country: "India",
        state: "Maharashtra",
    },
    {
        city: "Bhagalpur",
        latitude: "25.2500",
        longitude: "87.0167",
        country: "India",
        state: "Bihar",
    },
    {
        city: "Sikar",
        latitude: "27.6119",
        longitude: "75.1397",
        country: "India",
        state: "Rajasthan",
    },
    {
        city: "Tumkūr",
        latitude: "13.3300",
        longitude: "77.1000",
        country: "India",
        state: "Karnataka",
    },
    {
        city: "Quilon",
        latitude: "8.8853",
        longitude: "76.5864",
        country: "India",
        state: "Kerala",
    },
    {
        city: "Muzaffarnagar",
        latitude: "29.4708",
        longitude: "77.7033",
        country: "India",
        state: "Uttar Pradesh",
    },
    {
        city: "Bhilwara",
        latitude: "25.3500",
        longitude: "74.6333",
        country: "India",
        state: "Rajasthan",
    },
    {
        city: "Nizamabad",
        latitude: "18.6704",
        longitude: "78.1000",
        country: "India",
        state: "Telangana",
    },
    {
        city: "Bhatpara",
        latitude: "22.8667",
        longitude: "88.4167",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Kakinada",
        latitude: "16.9333",
        longitude: "82.2167",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Parbhani",
        latitude: "19.2704",
        longitude: "76.7600",
        country: "India",
        state: "Maharashtra",
    },
    {
        city: "Panihati",
        latitude: "22.6900",
        longitude: "88.3700",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Latūr",
        latitude: "18.4004",
        longitude: "76.5700",
        country: "India",
        state: "Maharashtra",
    },
    {
        city: "Rohtak",
        latitude: "28.9000",
        longitude: "76.5667",
        country: "India",
        state: "Haryana",
    },
    {
        city: "Rajapalaiyam",
        latitude: "9.4204",
        longitude: "77.5800",
        country: "India",
        state: "Tamil Nadu",
    },
    {
        city: "Ahmadnagar",
        latitude: "19.0833",
        longitude: "74.7333",
        country: "India",
        state: "Maharashtra",
    },
    {
        city: "Cuddapah",
        latitude: "14.4667",
        longitude: "78.8167",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Rajahmundry",
        latitude: "16.9833",
        longitude: "81.7833",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Alwar",
        latitude: "27.5667",
        longitude: "76.6167",
        country: "India",
        state: "Rajasthan",
    },
    {
        city: "Muzaffarpur",
        latitude: "26.1200",
        longitude: "85.3833",
        country: "India",
        state: "Bihar",
    },
    {
        city: "Bilaspur",
        latitude: "22.1500",
        longitude: "82.0167",
        country: "India",
        state: "Chhattisgarh",
    },
    {
        city: "Mathura",
        latitude: "27.4833",
        longitude: "77.6833",
        country: "India",
        state: "Uttar Pradesh",
    },
    {
        city: "Kamarhati",
        latitude: "22.6700",
        longitude: "88.3700",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Patiala",
        latitude: "30.3204",
        longitude: "76.3850",
        country: "India",
        state: "Punjab",
    },
    {
        city: "Saugor",
        latitude: "23.8504",
        longitude: "78.7500",
        country: "India",
        state: "Madhya Pradesh",
    },
    {
        city: "Bijapur",
        latitude: "16.8244",
        longitude: "75.7154",
        country: "India",
        state: "Karnataka",
    },
    {
        city: "Brahmapur",
        latitude: "19.3200",
        longitude: "84.8000",
        country: "India",
        state: "Odisha",
    },
    {
        city: "Shahjanpur",
        latitude: "27.8804",
        longitude: "79.9050",
        country: "India",
        state: "Uttar Pradesh",
    },
    {
        city: "Trichūr",
        latitude: "10.5200",
        longitude: "76.2100",
        country: "India",
        state: "Kerala",
    },
    {
        city: "Barddhaman",
        latitude: "23.2500",
        longitude: "87.8500",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Kulti",
        latitude: "23.7300",
        longitude: "86.8500",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Sambalpur",
        latitude: "21.4704",
        longitude: "83.9701",
        country: "India",
        state: "Odisha",
    },
    {
        city: "Purnea",
        latitude: "25.7800",
        longitude: "87.4700",
        country: "India",
        state: "Bihar",
    },
    {
        city: "Hisar",
        latitude: "29.1489",
        longitude: "75.7367",
        country: "India",
        state: "Haryana",
    },
    {
        city: "Firozabad",
        latitude: "27.1500",
        longitude: "78.3949",
        country: "India",
        state: "Uttar Pradesh",
    },
    {
        city: "Bidar",
        latitude: "17.9229",
        longitude: "77.5175",
        country: "India",
        state: "Karnataka",
    },
    {
        city: "Rampur",
        latitude: "28.8154",
        longitude: "79.0250",
        country: "India",
        state: "Uttar Pradesh",
    },
    {
        city: "Shiliguri",
        latitude: "26.7200",
        longitude: "88.4200",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Bali",
        latitude: "22.6500",
        longitude: "88.3400",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Panipat",
        latitude: "29.4004",
        longitude: "76.9700",
        country: "India",
        state: "Haryana",
    },
    {
        city: "Karimnagar",
        latitude: "18.4333",
        longitude: "79.1500",
        country: "India",
        state: "Telangana",
    },
    {
        city: "Bhuj",
        latitude: "23.2504",
        longitude: "69.8100",
        country: "India",
        state: "Gujarat",
    },
    {
        city: "Ichalkaranji",
        latitude: "16.7000",
        longitude: "74.4700",
        country: "India",
        state: "Maharashtra",
    },
    {
        city: "Tirupati",
        latitude: "13.6500",
        longitude: "79.4200",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Hospet",
        latitude: "15.2667",
        longitude: "76.4000",
        country: "India",
        state: "Karnataka",
    },
    {
        city: "aizawl",
        latitude: "23.7104",
        longitude: "92.7200",
        country: "India",
        state: "Mizoram",
    },
    {
        city: "Sannai",
        latitude: "24.1600",
        longitude: "80.8300",
        country: "India",
        state: "Madhya Pradesh",
    },
    {
        city: "Barasat",
        latitude: "22.2333",
        longitude: "88.4500",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Ratlam",
        latitude: "23.3167",
        longitude: "75.0667",
        country: "India",
        state: "Madhya Pradesh",
    },
    {
        city: "Handwara",
        latitude: "34.4000",
        longitude: "74.2800",
        country: "India",
        state: "Jammu and Kashmir",
    },
    {
        city: "Drug",
        latitude: "21.1900",
        longitude: "81.2800",
        country: "India",
        state: "Chhattisgarh",
    },
    {
        city: "Imphal",
        latitude: "24.8200",
        longitude: "93.9500",
        country: "India",
        state: "Manipur",
    },
    {
        city: "Anantapur",
        latitude: "14.6833",
        longitude: "77.6000",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Etawah",
        latitude: "26.7855",
        longitude: "79.0150",
        country: "India",
        state: "Uttar Pradesh",
    },
    {
        city: "Raichūr",
        latitude: "16.2104",
        longitude: "77.3550",
        country: "India",
        state: "Karnataka",
    },
    {
        city: "Ongole",
        latitude: "15.5000",
        longitude: "80.0500",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Bharatpur",
        latitude: "27.2172",
        longitude: "77.4900",
        country: "India",
        state: "Rajasthan",
    },
    {
        city: "Begusarai",
        latitude: "25.4200",
        longitude: "86.1300",
        country: "India",
        state: "Bihar",
    },
    {
        city: "Sonipat",
        latitude: "28.9958",
        longitude: "77.0114",
        country: "India",
        state: "Haryana",
    },
    {
        city: "Ramgundam",
        latitude: "18.8000",
        longitude: "79.4500",
        country: "India",
        state: "Telangana",
    },
    {
        city: "Hapur",
        latitude: "28.7437",
        longitude: "77.7628",
        country: "India",
        state: "Uttar Pradesh",
    },
    {
        city: "Uluberiya",
        latitude: "22.4700",
        longitude: "88.1100",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Porbandar",
        latitude: "21.6425",
        longitude: "69.6047",
        country: "India",
        state: "Gujarat",
    },
    {
        city: "Pali",
        latitude: "25.7725",
        longitude: "73.3233",
        country: "India",
        state: "Rajasthan",
    },
    {
        city: "Vizianagaram",
        latitude: "18.1167",
        longitude: "83.4167",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Puducherry",
        latitude: "11.9300",
        longitude: "79.8300",
        country: "India",
        state: "Puducherry",
    },
    {
        city: "Karnal",
        latitude: "29.6804",
        longitude: "76.9700",
        country: "India",
        state: "Haryana",
    },
    {
        city: "Nagercoil",
        latitude: "8.1700",
        longitude: "77.4300",
        country: "India",
        state: "Tamil Nadu",
    },
    {
        city: "Tanjore",
        latitude: "10.8000",
        longitude: "79.1500",
        country: "India",
        state: "Tamil Nadu",
    },
    {
        city: "Sambhal",
        latitude: "28.5800",
        longitude: "78.5500",
        country: "India",
        state: "Uttar Pradesh",
    },
    {
        city: "Naihati",
        latitude: "22.9000",
        longitude: "88.4200",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Secunderabad",
        latitude: "17.4500",
        longitude: "78.5000",
        country: "India",
        state: "Telangana",
    },
    {
        city: "Kharagpur",
        latitude: "22.3302",
        longitude: "87.3237",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Dindigul",
        latitude: "10.3500",
        longitude: "77.9500",
        country: "India",
        state: "Tamil Nadu",
    },
    {
        city: "Shimla",
        latitude: "31.1033",
        longitude: "77.1722",
        country: "India",
        state: "Himachal Pradesh",
    },
    {
        city: "Ingraj Bazar",
        latitude: "25.0000",
        longitude: "88.1500",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Ellore",
        latitude: "16.7000",
        longitude: "81.1000",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Puri",
        latitude: "19.8000",
        longitude: "85.8167",
        country: "India",
        state: "Odisha",
    },
    {
        city: "Haldia",
        latitude: "22.0257",
        longitude: "88.0583",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Nandyal",
        latitude: "15.4800",
        longitude: "78.4800",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Bulandshahr",
        latitude: "28.4104",
        longitude: "77.8484",
        country: "India",
        state: "Uttar Pradesh",
    },
    {
        city: "Chakradharpur",
        latitude: "22.7000",
        longitude: "85.6300",
        country: "India",
        state: "Jharkhand",
    },
    {
        city: "Bhiwani",
        latitude: "28.7833",
        longitude: "76.1333",
        country: "India",
        state: "Haryana",
    },
    {
        city: "Gurgaon",
        latitude: "28.4500",
        longitude: "77.0200",
        country: "India",
        state: "Haryana",
    },
    {
        city: "Burhanpur",
        latitude: "21.3004",
        longitude: "76.1300",
        country: "India",
        state: "Madhya Pradesh",
    },
    {
        city: "Khammam",
        latitude: "17.2500",
        longitude: "80.1500",
        country: "India",
        state: "Telangana",
    },
    {
        city: "Madhyamgram",
        latitude: "22.7000",
        longitude: "88.4500",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Ghandinagar",
        latitude: "23.2200",
        longitude: "72.6800",
        country: "India",
        state: "Gujarat",
    },
    {
        city: "Baharampur",
        latitude: "24.1000",
        longitude: "88.2500",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Mahbūbnagar",
        latitude: "16.7333",
        longitude: "77.9833",
        country: "India",
        state: "Telangana",
    },
    {
        city: "Mahesana",
        latitude: "23.6000",
        longitude: "72.4000",
        country: "India",
        state: "Gujarat",
    },
    {
        city: "adoni",
        latitude: "15.6300",
        longitude: "77.2800",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Raiganj",
        latitude: "25.6167",
        longitude: "88.1167",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Bhusaval",
        latitude: "21.0200",
        longitude: "75.8300",
        country: "India",
        state: "Maharashtra",
    },
    {
        city: "Bahraigh",
        latitude: "27.6204",
        longitude: "81.6699",
        country: "India",
        state: "Uttar Pradesh",
    },
    {
        city: "Shrirampur",
        latitude: "22.7500",
        longitude: "88.3400",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Tonk",
        latitude: "26.1505",
        longitude: "75.7900",
        country: "India",
        state: "Rajasthan",
    },
    {
        city: "Sirsa",
        latitude: "29.4904",
        longitude: "75.0300",
        country: "India",
        state: "Haryana",
    },
    {
        city: "Jaunpur",
        latitude: "25.7333",
        longitude: "82.6833",
        country: "India",
        state: "Uttar Pradesh",
    },
    {
        city: "Madanapalle",
        latitude: "13.5500",
        longitude: "78.5000",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Hugli",
        latitude: "22.9000",
        longitude: "88.3900",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Vellore",
        latitude: "12.9204",
        longitude: "79.1500",
        country: "India",
        state: "Tamil Nadu",
    },
    {
        city: "Alleppey",
        latitude: "9.5004",
        longitude: "76.3700",
        country: "India",
        state: "Kerala",
    },
    {
        city: "Cuddalore",
        latitude: "11.7500",
        longitude: "79.7500",
        country: "India",
        state: "Tamil Nadu",
    },
    {
        city: "Deo",
        latitude: "24.6561",
        longitude: "84.4356",
        country: "India",
        state: "Bihar",
    },
    {
        city: "Chirala",
        latitude: "15.8200",
        longitude: "80.3500",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Machilipatnam",
        latitude: "16.1667",
        longitude: "81.1333",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Medinipur",
        latitude: "22.4333",
        longitude: "87.3333",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Baramūla",
        latitude: "34.2000",
        longitude: "74.3400",
        country: "India",
        state: "Jammu and Kashmir",
    },
    {
        city: "Chandannagar",
        latitude: "22.8667",
        longitude: "88.3833",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Fatehpur",
        latitude: "25.8804",
        longitude: "80.8000",
        country: "India",
        state: "Uttar Pradesh",
    },
    {
        city: "Udipi",
        latitude: "13.3322",
        longitude: "74.7461",
        country: "India",
        state: "Karnataka",
    },
    {
        city: "Tenali",
        latitude: "16.2430",
        longitude: "80.6400",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Sitalpur",
        latitude: "27.6300",
        longitude: "80.7500",
        country: "India",
        state: "Uttar Pradesh",
    },
    {
        city: "Conjeeveram",
        latitude: "12.8308",
        longitude: "79.7078",
        country: "India",
        state: "Tamil Nadu",
    },
    {
        city: "Proddatūr",
        latitude: "14.7300",
        longitude: "78.5500",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Navsari",
        latitude: "20.8504",
        longitude: "72.9200",
        country: "India",
        state: "Gujarat",
    },
    {
        city: "Godhra",
        latitude: "22.7755",
        longitude: "73.6149",
        country: "India",
        state: "Gujarat",
    },
    {
        city: "Budaun",
        latitude: "28.0300",
        longitude: "79.0900",
        country: "India",
        state: "Uttar Pradesh",
    },
    {
        city: "Chittoor",
        latitude: "13.2000",
        longitude: "79.1167",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Haripur",
        latitude: "31.5200",
        longitude: "75.9800",
        country: "India",
        state: "Punjab",
    },
    {
        city: "Saharsa",
        latitude: "25.8800",
        longitude: "86.6000",
        country: "India",
        state: "Bihar",
    },
    {
        city: "Vidisha",
        latitude: "23.5239",
        longitude: "77.8061",
        country: "India",
        state: "Madhya Pradesh",
    },
    {
        city: "Pathankot",
        latitude: "32.2689",
        longitude: "75.6497",
        country: "India",
        state: "Punjab",
    },
    {
        city: "Nalgonda",
        latitude: "17.0500",
        longitude: "79.2700",
        country: "India",
        state: "Telangana",
    },
    {
        city: "Dibrugarh",
        latitude: "27.4833",
        longitude: "95.0000",
        country: "India",
        state: "Assam",
    },
    {
        city: "Balurghat",
        latitude: "25.2167",
        longitude: "88.7667",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Krishnanagar",
        latitude: "23.4000",
        longitude: "88.5000",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Fyzabad",
        latitude: "26.7504",
        longitude: "82.1700",
        country: "India",
        state: "Uttar Pradesh",
    },
    {
        city: "Silchar",
        latitude: "24.7904",
        longitude: "92.7900",
        country: "India",
        state: "Assam",
    },
    {
        city: "Shantipur",
        latitude: "23.2500",
        longitude: "88.4300",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Hindupur",
        latitude: "13.8300",
        longitude: "77.4900",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Erode",
        latitude: "11.3408",
        longitude: "77.7172",
        country: "India",
        state: "Tamil Nadu",
    },
    {
        city: "Jamuria",
        latitude: "23.7000",
        longitude: "87.0800",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Habra",
        latitude: "22.8300",
        longitude: "88.6300",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Ambala",
        latitude: "30.3786",
        longitude: "76.7725",
        country: "India",
        state: "Haryana",
    },
    {
        city: "Mauli",
        latitude: "30.7194",
        longitude: "76.7181",
        country: "India",
        state: "Punjab",
    },
    {
        city: "Kolar",
        latitude: "13.1333",
        longitude: "78.1333",
        country: "India",
        state: "Karnataka",
    },
    {
        city: "Shillong",
        latitude: "25.5744",
        longitude: "91.8789",
        country: "India",
        state: "Meghalaya",
    },
    {
        city: "Bhimavaram",
        latitude: "16.5333",
        longitude: "81.5333",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "New Delhi",
        latitude: "28.7000",
        longitude: "77.2000",
        country: "India",
        state: "Delhi",

    },
    {
        city: "Mandsaur",
        latitude: "24.0300",
        longitude: "75.0800",
        country: "India",
        state: "Madhya Pradesh",
    },
    {
        city: "Kumbakonam",
        latitude: "10.9805",
        longitude: "79.4000",
        country: "India",
        state: "Tamil Nadu",
    },
    {
        city: "Tiruvannamalai",
        latitude: "12.2604",
        longitude: "79.1000",
        country: "India",
        state: "Tamil Nadu",
    },
    {
        city: "Chicacole",
        latitude: "18.3000",
        longitude: "83.9000",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Bankura",
        latitude: "23.2500",
        longitude: "87.0667",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Mandya",
        latitude: "12.5242",
        longitude: "76.8958",
        country: "India",
        state: "Karnataka",
    },
    {
        city: "Hassan",
        latitude: "13.0050",
        longitude: "76.1028",
        country: "India",
        state: "Karnataka",
    },
    {
        city: "Yavatmal",
        latitude: "20.4000",
        longitude: "78.1333",
        country: "India",
        state: "Maharashtra",
    },
    {
        city: "Pilibhit",
        latitude: "28.6400",
        longitude: "79.8100",
        country: "India",
        state: "Uttar Pradesh",
    },
    {
        city: "Palghat",
        latitude: "10.7792",
        longitude: "76.6547",
        country: "India",
        state: "Kerala",
    },
    {
        city: "Abohar",
        latitude: "30.1204",
        longitude: "74.2900",
        country: "India",
        state: "Punjab",
    },
    {
        city: "Palakollu",
        latitude: "16.5333",
        longitude: "81.7333",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Kanchrapara",
        latitude: "22.9700",
        longitude: "88.4300",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Port Blair",
        latitude: "11.6667",
        longitude: "92.7500",
        country: "India",
        state: "Andaman and Nicobar Islands",
    },
    {
        city: "Alipur Duar",
        latitude: "26.4837",
        longitude: "89.5667",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Hathras",
        latitude: "27.6000",
        longitude: "78.0500",
        country: "India",
        state: "Uttar Pradesh",
    },
    {
        city: "Guntakal",
        latitude: "15.1700",
        longitude: "77.3800",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Navadwip",
        latitude: "23.4088",
        longitude: "88.3657",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Basirhat",
        latitude: "22.6572",
        longitude: "88.8942",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Halisahar",
        latitude: "22.9500",
        longitude: "88.4200",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Rishra",
        latitude: "22.7100",
        longitude: "88.3500",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Dharmavaram",
        latitude: "14.4142",
        longitude: "77.7150",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Baidyabati",
        latitude: "22.7900",
        longitude: "88.3200",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Darjeeling",
        latitude: "27.0417",
        longitude: "88.2631",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Sopur",
        latitude: "34.3000",
        longitude: "74.4700",
        country: "India",
        state: "Jammu and Kashmir",
    },
    {
        city: "Gudivada",
        latitude: "16.4300",
        longitude: "80.9900",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Adilabad",
        latitude: "19.6667",
        longitude: "78.5333",
        country: "India",
        state: "Telangana",
    },
    {
        city: "Titagarh",
        latitude: "22.7400",
        longitude: "88.3700",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Chittaurgarh",
        latitude: "24.8894",
        longitude: "74.6239",
        country: "India",
        state: "Rajasthan",
    },
    {
        city: "Narasaraopet",
        latitude: "16.2360",
        longitude: "80.0540",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Dam Dam",
        latitude: "22.6200",
        longitude: "88.4200",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Valparai",
        latitude: "10.3204",
        longitude: "76.9700",
        country: "India",
        state: "Tamil Nadu",
    },
    {
        city: "Osmanabad",
        latitude: "18.1667",
        longitude: "76.0500",
        country: "India",
        state: "Maharashtra",
    },
    {
        city: "Champdani",
        latitude: "22.8000",
        longitude: "88.3700",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Bangaon",
        latitude: "23.0700",
        longitude: "88.8200",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Khardah",
        latitude: "22.7200",
        longitude: "88.3800",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Tadpatri",
        latitude: "14.9200",
        longitude: "78.0200",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Jalpaiguri",
        latitude: "26.5167",
        longitude: "88.7333",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Suriapet",
        latitude: "17.1500",
        longitude: "79.6167",
        country: "India",
        state: "Telangana",
    },
    {
        city: "Tadepallegūdem",
        latitude: "16.8333",
        longitude: "81.5000",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Bansbaria",
        latitude: "22.9700",
        longitude: "88.4000",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Negapatam",
        latitude: "10.7667",
        longitude: "79.8333",
        country: "India",
        state: "Tamil Nadu",
    },
    {
        city: "Bhadreswar",
        latitude: "22.8200",
        longitude: "88.3500",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Chilakalūrupet",
        latitude: "16.0892",
        longitude: "80.1672",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Kalyani",
        latitude: "22.9750",
        longitude: "88.4344",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Gangtok",
        latitude: "27.3300",
        longitude: "88.6200",
        country: "India",
        state: "Sikkim",
    },
    {
        city: "Kohima",
        latitude: "25.6667",
        longitude: "94.1194",
        country: "India",
        state: "Nagaland",
    },
    {
        city: "Khambhat",
        latitude: "22.3131",
        longitude: "72.6194",
        country: "India",
        state: "Gujarat",
    },
    {
        city: "Aurangabad",
        latitude: "24.7704",
        longitude: "84.3800",
        country: "India",
        state: "Bihar",
    },
    {
        city: "Emmiganūr",
        latitude: "15.7333",
        longitude: "77.4833",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Rayachoti",
        latitude: "14.0500",
        longitude: "78.7500",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Kavali",
        latitude: "14.9123",
        longitude: "79.9944",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Mancheral",
        latitude: "18.8679",
        longitude: "79.4639",
        country: "India",
        state: "Telangana",
    },
    {
        city: "Kadiri",
        latitude: "14.1200",
        longitude: "78.1700",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Ootacamund",
        latitude: "11.4086",
        longitude: "76.6939",
        country: "India",
        state: "Tamil Nadu",
    },
    {
        city: "Anakapalle",
        latitude: "17.6800",
        longitude: "83.0200",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Sirsilla",
        latitude: "18.3800",
        longitude: "78.8300",
        country: "India",
        state: "Telangana",
    },
    {
        city: "Kamareddipet",
        latitude: "18.3167",
        longitude: "78.3500",
        country: "India",
        state: "Telangana",
    },
    {
        city: "Paloncha",
        latitude: "17.5815",
        longitude: "80.6765",
        country: "India",
        state: "Telangana",
    },
    {
        city: "Kottagūdem",
        latitude: "17.5500",
        longitude: "80.6300",
        country: "India",
        state: "Telangana",
    },
    {
        city: "Tanuku",
        latitude: "16.7500",
        longitude: "81.7000",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Bodhan",
        latitude: "18.6700",
        longitude: "77.9000",
        country: "India",
        state: "Telangana",
    },
    {
        city: "Karūr",
        latitude: "10.9504",
        longitude: "78.0833",
        country: "India",
        state: "Tamil Nadu",
    },
    {
        city: "Mangalagiri",
        latitude: "16.4300",
        longitude: "80.5500",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Kairana",
        latitude: "29.4000",
        longitude: "77.2000",
        country: "India",
        state: "Uttar Pradesh",
    },
    {
        city: "Markapur",
        latitude: "15.7350",
        longitude: "79.2700",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Malaut",
        latitude: "30.1900",
        longitude: "74.4990",
        country: "India",
        state: "Punjab",
    },
    {
        city: "Bapatla",
        latitude: "15.8889",
        longitude: "80.4700",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Badvel",
        latitude: "14.7500",
        longitude: "79.0500",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Jorhat",
        latitude: "26.7500",
        longitude: "94.2167",
        country: "India",
        state: "Assam",
    },
    {
        city: "Koratla",
        latitude: "18.8200",
        longitude: "78.7200",
        country: "India",
        state: "Telangana",
    },
    {
        city: "Pulivendla",
        latitude: "14.4167",
        longitude: "78.2333",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Jaisalmer",
        latitude: "26.9167",
        longitude: "70.9167",
        country: "India",
        state: "Rajasthan",
    },
    {
        city: "Tadepalle",
        latitude: "16.4667",
        longitude: "80.6000",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Armūr",
        latitude: "18.7900",
        longitude: "78.2900",
        country: "India",
        state: "Telangana",
    },
    {
        city: "Jatani",
        latitude: "20.1700",
        longitude: "85.7000",
        country: "India",
        state: "Odisha",
    },
    {
        city: "Gadwal",
        latitude: "16.2300",
        longitude: "77.8000",
        country: "India",
        state: "Telangana",
    },
    {
        city: "Nagari",
        latitude: "13.3300",
        longitude: "79.5800",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Wanparti",
        latitude: "16.3610",
        longitude: "78.0627",
        country: "India",
        state: "Telangana",
    },
    {
        city: "Ponnūru",
        latitude: "16.0667",
        longitude: "80.5667",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Vinukonda",
        latitude: "16.0500",
        longitude: "79.7500",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Itanagar",
        latitude: "27.1000",
        longitude: "93.6200",
        country: "India",
        state: "Arunachal Pradesh",
    },
    {
        city: "Tezpur",
        latitude: "26.6338",
        longitude: "92.8000",
        country: "India",
        state: "Assam",
    },
    {
        city: "Narasapur",
        latitude: "16.4333",
        longitude: "81.6833",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Kothapet",
        latitude: "19.3333",
        longitude: "79.4833",
        country: "India",
        state: "Telangana",
    },
    {
        city: "Macherla",
        latitude: "16.4800",
        longitude: "79.4300",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Kandukūr",
        latitude: "15.2165",
        longitude: "79.9042",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Samalkot",
        latitude: "17.0531",
        longitude: "82.1695",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Bobbili",
        latitude: "18.5667",
        longitude: "83.4167",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Sattenapalle",
        latitude: "16.3962",
        longitude: "80.1497",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Vrindavan",
        latitude: "27.5806",
        longitude: "77.7006",
        country: "India",
        state: "Uttar Pradesh",
    },
    {
        city: "Mandapeta",
        latitude: "16.8700",
        longitude: "81.9300",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Belampalli",
        latitude: "19.0558",
        longitude: "79.4931",
        country: "India",
        state: "Telangana",
    },
    {
        city: "Bhimunipatnam",
        latitude: "17.8864",
        longitude: "83.4471",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Nandod",
        latitude: "21.8704",
        longitude: "73.5026",
        country: "India",
        state: "Gujarat",
    },
    {
        city: "Pithapuram",
        latitude: "17.1167",
        longitude: "82.2667",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Punganūru",
        latitude: "13.3667",
        longitude: "78.5833",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Puttūr",
        latitude: "13.4500",
        longitude: "79.5500",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Jalor",
        latitude: "25.3500",
        longitude: "72.6167",
        country: "India",
        state: "Rajasthan",
    },
    {
        city: "Palmaner",
        latitude: "13.2000",
        longitude: "78.7500",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Dholka",
        latitude: "22.7200",
        longitude: "72.4700",
        country: "India",
        state: "Gujarat",
    },
    {
        city: "Jaggayyapeta",
        latitude: "16.8920",
        longitude: "80.0976",
        country: "India",
        state: "Telangana",
    },
    {
        city: "Tuni",
        latitude: "17.3500",
        longitude: "82.5500",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Amalapuram",
        latitude: "16.5833",
        longitude: "82.0167",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Jagtial",
        latitude: "18.8000",
        longitude: "78.9300",
        country: "India",
        state: "Telangana",
    },
    {
        city: "Vikarabad",
        latitude: "17.3300",
        longitude: "77.9000",
        country: "India",
        state: "Telangana",
    },
    {
        city: "Venkatagiri",
        latitude: "13.9667",
        longitude: "79.5833",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Sihor",
        latitude: "21.7000",
        longitude: "71.9700",
        country: "India",
        state: "Gujarat",
    },
    {
        city: "Jangaon",
        latitude: "17.7200",
        longitude: "79.1800",
        country: "India",
        state: "Telangana",
    },
    {
        city: "Mandamari",
        latitude: "18.9822",
        longitude: "79.4811",
        country: "India",
        state: "Telangana",
    },
    {
        city: "Metpalli",
        latitude: "18.8297",
        longitude: "78.5878",
        country: "India",
        state: "Telangana",
    },
    {
        city: "Repalle",
        latitude: "16.0200",
        longitude: "80.8500",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Bhainsa",
        latitude: "19.1000",
        longitude: "77.9667",
        country: "India",
        state: "Telangana",
    },
    {
        city: "Jasdan",
        latitude: "22.0300",
        longitude: "71.2000",
        country: "India",
        state: "Gujarat",
    },
    {
        city: "Jammalamadugu",
        latitude: "14.8500",
        longitude: "78.3800",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Rameswaram",
        latitude: "9.2800",
        longitude: "79.3000",
        country: "India",
        state: "Tamil Nadu",
    },
    {
        city: "Addanki",
        latitude: "15.8110",
        longitude: "79.9738",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Nidadavole",
        latitude: "16.9200",
        longitude: "81.6700",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Bodupal",
        latitude: "17.4139",
        longitude: "78.5783",
        country: "India",
        state: "Telangana",
    },
    {
        city: "Rajgir",
        latitude: "25.0300",
        longitude: "85.4200",
        country: "India",
        state: "Bihar",
    },
    {
        city: "Rajaori",
        latitude: "33.3800",
        longitude: "74.3000",
        country: "India",
        state: "Jammu and Kashmir",
    },
    {
        city: "Naini Tal",
        latitude: "29.3919",
        longitude: "79.4542",
        country: "India",
        state: "Uttarakhand",
    },
    {
        city: "Channarayapatna",
        latitude: "12.9000",
        longitude: "76.3900",
        country: "India",
        state: "Karnataka",
    },
    {
        city: "Maihar",
        latitude: "24.2700",
        longitude: "80.7500",
        country: "India",
        state: "Madhya Pradesh",
    },
    {
        city: "Panaji",
        latitude: "15.4800",
        longitude: "73.8300",
        country: "India",
        state: "Goa",
    },
    {
        city: "Junnar",
        latitude: "19.2000",
        longitude: "73.8800",
        country: "India",
        state: "Maharashtra",
    },
    {
        city: "Amudalavalasa",
        latitude: "18.4167",
        longitude: "83.9000",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Daman",
        latitude: "20.4170",
        longitude: "72.8500",
        country: "India",
        state: "Gujarat",
    },
    {
        city: "Kovvūr",
        latitude: "17.0167",
        longitude: "81.7333",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Solan",
        latitude: "30.9200",
        longitude: "77.1200",
        country: "India",
        state: "Himachal Pradesh",
    },
    {
        city: "Dwarka",
        latitude: "22.2403",
        longitude: "68.9686",
        country: "India",
        state: "Gujarat",
    },
    {
        city: "Pathanamthitta",
        latitude: "9.2647",
        longitude: "76.7872",
        country: "India",
        state: "Kerala",
    },
    {
        city: "Kodaikanal",
        latitude: "10.2300",
        longitude: "77.4800",
        country: "India",
        state: "Tamil Nadu",
    },
    {
        city: "Udhampur",
        latitude: "32.9300",
        longitude: "75.1300",
        country: "India",
        state: "Jammu and Kashmir",
    },
    {
        city: "Giddalūr",
        latitude: "15.3784",
        longitude: "78.9265",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Yellandu",
        latitude: "17.6000",
        longitude: "80.3300",
        country: "India",
        state: "Telangana",
    },
    {
        city: "Shrirangapattana",
        latitude: "12.4181",
        longitude: "76.6947",
        country: "India",
        state: "Karnataka",
    },
    {
        city: "Angamali",
        latitude: "10.1960",
        longitude: "76.3860",
        country: "India",
        state: "Kerala",
    },
    {
        city: "Umaria",
        latitude: "23.5245",
        longitude: "80.8365",
        country: "India",
        state: "Madhya Pradesh",
    },
    {
        city: "Fatehpur Sikri",
        latitude: "27.0911",
        longitude: "77.6611",
        country: "India",
        state: "Uttar Pradesh",
    },
    {
        city: "Mangūr",
        latitude: "17.9373",
        longitude: "80.8185",
        country: "India",
        state: "Telangana",
    },
    {
        city: "Pedana",
        latitude: "16.2667",
        longitude: "81.1667",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Uran",
        latitude: "18.8900",
        longitude: "72.9500",
        country: "India",
        state: "Maharashtra",
    },
    {
        city: "Chimakurti",
        latitude: "15.5819",
        longitude: "79.8680",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Devarkonda",
        latitude: "16.7000",
        longitude: "78.9333",
        country: "India",
        state: "Telangana",
    },
    {
        city: "Bandipura",
        latitude: "34.4225",
        longitude: "74.6375",
        country: "India",
        state: "Jammu and Kashmir",
    },
    {
        city: "Silvassa",
        latitude: "20.2666",
        longitude: "73.0166",
        country: "India",
        state: "Dadra and Nagar Haveli",
    },
    {
        city: "Pamidi",
        latitude: "14.9500",
        longitude: "77.5833",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Narasannapeta",
        latitude: "18.4151",
        longitude: "84.0447",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Jaynagar-Majilpur",
        latitude: "22.1772",
        longitude: "88.4258",
        country: "India",
        state: "West Bengal",
    },
    {
        city: "Khed Brahma",
        latitude: "24.0299",
        longitude: "73.0463",
        country: "India",
        state: "Gujarat",
    },
    {
        city: "Khajuraho",
        latitude: "24.8500",
        longitude: "79.9333",
        country: "India",
        state: "Madhya Pradesh",
    },
    {
        city: "Koilkuntla",
        latitude: "15.2333",
        longitude: "78.3167",
        country: "India",
        state: "Andhra Pradesh",
    },
    {
        city: "Diu",
        latitude: "20.7197",
        longitude: "70.9904",
        country: "India",
        state: "Daman and Diu",
    },
    {
        city: "Kulgam",
        latitude: "33.6400",
        longitude: "75.0200",
        country: "India",
        state: "Jammu and Kashmir",
    },
    {
        city: "Gauripur",
        latitude: "26.0800",
        longitude: "89.9700",
        country: "India",
        state: "Assam",
    },
    {
        city: "Abu",
        latitude: "24.5925",
        longitude: "72.7083",
        country: "India",
        state: "Rajasthan",
    },
    {
        city: "Curchorem",
        latitude: "15.2500",
        longitude: "74.1000",
        country: "India",
        state: "Goa",
    },
    {
        city: "Kavaratti",
        latitude: "10.5626",
        longitude: "72.6369",
        country: "India",
        state: "Lakshadweep",
    },
    {
        city: "Panchkula",
        latitude: "30.6915",
        longitude: "76.8537",
        country: "India",
        state: "Haryana",
    },
    {
        city: "Kagaznagar",
        latitude: "19.3316",
        longitude: "79.4661",
        country: "India",
        state: "Telangana",
    }
];